### ISSUE TITLE
Badger.ReportViewer: evaluations can have multiple episodes

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#100]
If an experiment has several episodes per evaluation, so far, only the first is taken into account in the report viewer. They all should be displayed and have stats calculated separately. They have to be easy to read.

For example: if we measure the performance of a wind turbine controller under different average wind-speeds, we want to know how the controller performed with each one and, also know the statistics of each episode in the evaluation, and the averages

**Comment by ladm2110** [comment]
Could you post some visual aid?? I am not sure what the problem is...

**Comment by borjafdezgauna** [comment]
Please read this:

https://github.com/borjafdezgauna/RLSimion/wiki/RLSimion#experiment-definition

**Comment by borjafdezgauna** [comment]
Not a priority any more
