### ISSUE TITLE
Badger.ExperimentEditor: initial checks

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#103]
On starting Badger, it should be checked that the exe files (RLSimion.exe, ....) and definitions.xml exist. Show an error otherwise

**Comment by alegd** [comment]
Should we give the option to choose the right directory where the files could be? Or would be better if we just show up a message box with the error and then close the app? 

Also I was wondering if would be necessary to check for other config files besides "definitions.xml".

**Comment by borjafdezgauna** [comment]
mmmm i think the directory should be fixed and an error in a message box
should be fine...
besides definitions.xml, the exe/dll files needed to run the experiments
(those in <exe>/<pre> tags) should be checked

2017 mai. 28 6:06 AM erabiltzaileak hau idatzi du ("José Alejandro Guerra
Denis" <notifications@github.com>):

**Comment by alegd** [comment]
Done. I'm assuming all experiments in the same app require the same files to run.

**Comment by borjafdezgauna** [comment]
Sounds reasonable :)
