### ISSUE TITLE
Badger.ExperimentEditor: apply timelines to numeric parameters

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#108]
In RLSimion's source code, parameters associated to real numbers are defined as either DOUBLE_PARAM or as a BRANCH of Class="CNumericValue-Factory", which can hold different types of "schedules":
```
<CLASS Name="CNumericValue-Factory">
    <CHOICE Name="Schedule" Class="CNumericValue" Comment="Schedule-type">
      <CHOICE-ELEMENT Name="Constant" Class="CConstantValue"/>
      <CHOICE-ELEMENT Name="Linear-Schedule" Class="CInterpolatedValue"/>
      <CHOICE-ELEMENT Name="Simple-Linear-Decay" Class="CSimpleEpisodeLinearSchedule"/>
      <CHOICE-ELEMENT Name="Bhatnagar-Schedule" Class="CBhatnagarSchedule"/>
    </CHOICE>
  </CLASS>
```
This means that in the source code we already have to specify whether a real number will be constant during the experiment (DOUBLE_PARAM) or it can be scheduled. Instead of this, it would be more flexible if all parameters were defined as DOUBLE_PARAM and then assigned a timeline (timeline=schedule) manually in the editor. This timeline should have the same options that now schedules values have, but a part should be hard-coded in the editor to "override" the output of DoubleValueConfigViewModel when a timeline is associated.
More on the object hierarchy in Badger:

https://github.com/borjafdezgauna/RLSimion/wiki/Badger-object-hierarchy

**Comment by alegd** [comment]
If I get this straight the goal is to have every real number value in the experiment editor as a DOUBLE_PARAM and then somehow be able to assign to each of this values a schedule. Right?

**Comment by borjafdezgauna** [comment]
Yep, that's it! This involves making changes to both Badger and RLSimion, so I think the best way to approach this is to do the Badger part in a different branch with a manually changed "definitions.xml" file (all schedules defined as DOUBLE_PARAM), and when it's done, change RLSimion accordingly

**Comment by borjafdezgauna** [comment]
For now, I think we can discard this.... not a priority
