### ISSUE TITLE
HerdAgent: more info about the machine

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#110]
The herd agent answers to discovery messages with the number of processors, the version of the agent, and the state. It would be very helpful if, additionally, it sent too:
-whether it's a x64 or a x86 machine
-the amount of memory
-the average load of the processors in the last 10 minutes? (http://stackoverflow.com/questions/278071/how-to-get-the-cpu-usage-in-c)
-CUDA support and version

This info could be displayed in Badger.ShepherdView as additional columns in the list of agents.

Look at HerdAgent.getAgentDescription() in Herd/HerdAgent.cs

**Comment by alegd** [comment]
Why 10 minutes to show average load? This time its attached to some specific reason or it is just a random time interval that can be changed? Just out of curiosity.

**Comment by borjafdezgauna** [comment]
Absolutely random :)

2017 mai. 22 6:43 PM erabiltzaileak hau idatzi du ("José Alejandro Guerra
Denis" <notifications@github.com>):

**Comment by borjafdezgauna** [comment]
[Added CUDA support]

**Comment by aserrin55** [comment]
When I tried to run Badger I found an error in the **HeardAgent.cs** file. Both _getProperty (HerdAgent.TotalMemoryTag)_ and _getProperty (HerdAgent.ProcessorLoadTag)_ returned "n/a" on my computer, so when the method tries to parse the double returns an exception (An exception of type 'System.FormatException' )

I have solved this by simply comparing the string it returns like this, in both functions:

 get {
                string err = "n/a";
                if (getProperty(HerdAgent.ProcessorLoadTag).Equals(err))
                {
                    return 0.0;
                }
                else return Double.Parse(getProperty(HerdAgent.ProcessorLoadTag));
            }

**Comment by alegd** [comment]
Yeah, that seems about right. That problem rise to me too the first time, I thought I had it fixed, obviously I was wrong. Nevertheless you can see the right info by building and then reinstalling the HerdAgent service.

**Comment by borjafdezgauna** [comment]
Tested. Badger works fine with both the previous version and the new one
