### ISSUE TITLE
ExperimentMonitor: problems monitoring more than one remote machine

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#111]
When I use more than one remote machine, the plots/progress bars seem to be "shared". 

For example, if 2 machines run 3 experiments each, the first 3 experimental units show no information, but the plots for the next 3 use 2 different colors (I guess, one color for each experimental unit) and the progress bar "flickers" between the progress value of the two different experimental units "sharing" the monitor view.

My guess is machine1/expUnit1's output is being directed to the same experimental unit monitoring view as machine2/expUnit2

http://imgur.com/kn2ZO7U

**Comment by alegd** [comment]
I think the problem have been fixed with the latest commit. I'll wait for a revision from the team though before I get to close this issue. Kind regards.

**Comment by borjafdezgauna** [comment]
Checked it: I think that it works properly now. Merci!
