### ISSUE TITLE
Badger & HerdAgent security concerns

### ISSUE THREAD

**Issue by zimmerrol** [borjafdezgauna/RLSimion#115]
At the moment Badger sends the executable RLSimion.exe and the required libraries after launching a job on a herdagent via the `SendFile` method of the `NetTransfer.cs` file. After receiving the files, `RLSimion.exe` will be executed as a `SYSTEM` user and can therefore modify almost everything on the clients device. As there are no further security checks during the file transmission this can be a great security risk: One only has to compromise one computer in a network which contains other devices containing the HerdAgent to easily infect them with malicious software, too.

To solve this issue there are at least 2 things which come to my mind:

- The `RLSimion.exe` shall not be executed by the `SYSTEM` user, but a normal user account, which can be specified in the local clients settings
- The communication between the HerdAgent and Badger has to be encrypted and there needs to be a certain type of user authentification

Any thoughts on this?

**Comment by borjafdezgauna** [comment]
You are totally right about this, though security is not very high on my priority list because the herd agent service is not meant to be used outside a controlled environment. My personal opinion is that:
-it's ok for the executable to be run with system permissions, because this allows us to create/modify files we wouldn't be allowed otherwise. Not sure 100% about what we wouldn't be able to do though... I recall there was something I needed system permissions for, but can't remember what for
-communications should be encrypted in such a way that only the administrator of the computers is allowed to send jobs

**Comment by zimmerrol** [comment]
What files are we currently modifing for which one needs `SYSTEM`s permissions? I thought that the HerdAgent is just saving the binaries and the experiments in the `temp` directory and executes them. To solve the issue, that a normal user without administrative priviliges might not be allowed to access these files, we could save that files in the `%appdata%` directory (which makes in my eyes more sense, as they are no essential part of the service itself).
Doing this, the problem could be solved like this:
After the service has been installed the user has to select a user account which will be used for the execution of the experiments. This setting is saved in the `%program files%` directory. When the service is invoked and has to run an experiment, it can now save the binaries in the `%appdata%`directory of the previously specified user. Then it can spawn the `RLSimion.exe` process within the context of this user. 

Or are there reasons against this approach?

**Comment by borjafdezgauna** [comment]
There used to be a button in Badger that allowed us to send a newer version of the service and update the service just be overwritting it. It wasn't elegant, but I seem to recall that was the reason I wanted `SYSTEM` privileges. That being said, I can't think of any reason for that approach not to work. A very good idea in my opinion! Feel free to assign this issue to yourself if you feel motivated

**Comment by zimmerrol** [comment]
A first implementation of the above described solution can be found in [commit 78696c9f189050ee978cbf1a5fb48bf240484c09](https://github.com/borjafdezgauna/RLSimion/commit/78696c9f189050ee978cbf1a5fb48bf240484c09).
I implemented these additional security features in a way, that they can be used but they can also be "turned off" by the user if he desires so - by default they are deactivated at the moment. 
If activated, the `RLSimion.exe` will now be executed in the `%appdata%` directory of a specified user. This is still done as`SYSTEM` user, but all elevated privileges are discarded, so that the risk of harmful code executions is reduced.
