### ISSUE TITLE
Badger.ReportViewer Illustration of Value Functions

### ISSUE THREAD

**Issue by zimmerrol** [borjafdezgauna/RLSimion#116]
I think it would be sometimes very helpful to see a visualization of the value functions of the experiment. As long as the space is not more than two dimensional this should not be too hard to implement. For higher dimensions one could later add an option to plot the `2D` slices of the `n` dimensional space along two of the `n` axes of it.

**Comment by borjafdezgauna** [comment]
Good idea. Has crossed my mind quite a lot of times. How do you propose doing it?:
-in real time in debug version: 2d graphs should be added to the renderer
-in the report viewer after: the value functions should be saved (every n episodes? only at the end?) and then explore the logged value function within the report viewer

**Comment by zimmerrol** [comment]
I think both ideas are useful. But I think one should start with the second point because it seems to be a little bit easier (in my opinion). 
I think that the value functions should be saved every n episodes... I am not quiet sure how much space they consume or how much time the saving needs; so maybe one can even save them every episode.

**Comment by borjafdezgauna** [comment]
Well, if a value function has n weights, then the uncompressed file would be n*sizeof(float/double) bytes

For example, in the robot-control problem, a VFunction with 2 variables (x-position and y-position), 20 features each, that would make a total of 20^2*8 bytes (in case doubles are used)= 3200 bytes
But this grows rather quickly, in the pullbox-1 task, a VFunction with 4 variables (position of the robot and the box) and 20 features each, that would make 1.280.000 bytes
And a QFunction on this same task with two action variables (20 features each): 512 Mb

So there's no easy answer for it... we could save only increments or compressed files

**Comment by zimmerrol** [comment]
Hm. Okay. Maybe it will be enough just to save it at the end of the experiment. I think, otherwise there will be too much data.

**Comment by borjafdezgauna** [comment]
I think that the saving of functions was already implemented in CLinearVFA... feel free to assign this issue to yourself and go for it!
When you are ready to work on the Report Viewer part, we may have to discuss how to approach it because right now only forks and fork values are shown... maybe a list of experimental units could be shown too, giving the chance to draw the log (SimionLogViewer) or plot the value functions. Both lists in a tab control maybe?

**Comment by borjafdezgauna** [comment]
Functions are now properly viewed. It could help to get cooler looking views, but it works nice enough for now
