### ISSUE TITLE
RLSimionLib Add information about successfully finished episodes

### ISSUE THREAD

**Issue by zimmerrol** [borjafdezgauna/RLSimion#117]
I thought that adding information about whether the agent was able to solve the problem or failed would be interesting analyzing the results. So, one could maybe modify the `setTerminalState` of the `CExperiment` class, so that it accepts a `bool` value indicating whether the episode has been finished successfully or not.

**Comment by borjafdezgauna** [comment]
mmmmm not sure about this. Isn't the reward itself a good way to know whether the problem was solved?

Adding a flag to `setTerminalState` is easy enough, but would do you propose to do with it?

**Comment by zimmerrol** [comment]
Some problems (at least in the papers I read so far) are described in such a way, that the experiment is either terminated after a specified number of seconds or when a end-state is achieved. This end-states can either be good or bad. For example the mountain car is sometimes described in a way, that there is a constant  reward of -1.0, for each position, and only the final position on the right side gives a reward of 1.0.... So it is not easy to see, just by looking at the average reward of an episode if it was completed successfully or failed.
Or do I miss something?

**Comment by borjafdezgauna** [comment]
Well, the average reward will be higher the less episodes it took to reach the positive reward in a terminal state.
Most continuous control problems don't have such terminal states, that's I chose to plot the average rewards as a compromise that works with both kinds of problems
