### ISSUE TITLE
Already defined references in freeglut

### ISSUE THREAD

**Issue by zimmerrol** [borjafdezgauna/RLSimion#176]
**Describe the bug**
Not strictly a bug, but I see dozens of linking warnings when I compile the solution. A lot of references seem to be defined twice. We should have a look at it and fix it.

**To Reproduce**
1. Compile the solution
2. See warnings

**Expected behavior**

**Desktop:**
 - OS: Windows 10
 - Version: 1.3.2

**Comment by borjafdezgauna** [comment]
I will have a look into it. It seems that one of the 3rd-party libraries is linked by two different projects used together in a third one
