### ISSUE TITLE
Herd Agent 1.3.2 fails to execute experiments on the FAST simulator

### ISSUE THREAD

**Issue by xabierlarrucea** [borjafdezgauna/RLSimion#179]
To reproduce the issue, just send any experiment that uses FASTWorld to a v1.3.2 agent. After creating the wind files, the agent will hang.

I checked that agents <=v1.2.3 don't have this problem and work properly, so there must have been a change between both versions that introduced the error

**Comment by borjafdezgauna** [comment]
I think I have fixed it. Description of the cause/solution in the commit. Needs to be tested in Linux and I will do that asap. Thanks!
