### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#23]
Remove all the resume stuff and simplify the interface: just a button (with the name of the branch??)

**Comment by utercero** [comment]
Background for the button:
White:ok
Red:the validation failed
Orange:defaultValue and validated

**Comment by utercero** [comment]
create validate(bool isConstrucor)
call validate(true) from constructor as set color red or orange
call validate(false) from other methods and set color red or white
public override valiate()
{
     validate(false);
}
