### ISSUE TITLE
Different extensions for experiments and batches

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#30]
Experiments and batches (experiment tree) should have a different extension to avoid loading an experiment as an experiment tree and the other way around.

-.exp.xml for experiment files
-.bat.xml for experiment trees

??

**Comment by utercero** [comment]
.xml is romoved from extension because it is funny to see .exp.xml in the openFileDialog. 
*.expe from experiments
*.tree from trees
