### ISSUE TITLE
Use the DLL to check input/output file conflicts in AppXML

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#45]
The function to be called:

int getIOFiles(const char\* xmlFilename,char\* pBuffer,int bufferSize)

xmlFilename: path to the config xml file
pBuffer: buffer of memory allocated by the caller (XMLApp). 10Kb of memory should be more than enough
bufferSize: size allocated for the buffer

**Comment by utercero** [comment]
The dll is available from AppXML
