### ISSUE TITLE
Deep learning: start tests and try to integrate it

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#66]

**Comment by zimmerrol** [comment]
After some reading I think that Caffe is a better choice to implement at first compared to tensorflow: The possibility of defining the model in a seperate .prototxt which can be read and written by humans offers a rich variety and a good user experience in my opinion.
Furthermore, I think that this tool http://ethereon.github.io/netscope/quickstart.html is also very interesting and can maybe be used in Badger to edit the neural networks later.

**Comment by borjafdezgauna** [comment]
Yes, that tool sounds really intetesting!

2017 abu. 19 3:09 PM erabiltzaileak hau idatzi du ("Roland Zimmermann" <
notifications@github.com>):

**Comment by zimmerrol** [comment]
After some more thoughts I switched from `caffe` to Microsoft's `CNTK`, as it has a better support for Visual Studio 2017 (at the moment at least). I [implemented ](https://github.com/FlashTek/neural-network-gui)a GUI to design the network architecture, a custom data format to store the network architectures (to transfer it to the HerdAgents for example), and a C++ library/program which can load this structures and create a trainable `CNTK` network model. Now there is only the question how one can integrate this in the most comfortable way into `Badger`. And how can implement the NN in the `RLSimion` framework exactly.
