### ISSUE TITLE
Badger.ExperimentMonitor should read experiments from the batch file

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#96]
Instead of getting a list of pending experiments, this list should be read from the batch file directly

**Comment by alegd** [comment]
Hi, I was trying to understand what you really want with this but no luck yet... can you give me more information  to get some background.

**Comment by borjafdezgauna** [comment]
When the "launch" button is pressed:

- WindowViewModel.runExperiments() is executed. This method:
    - saves the batch file with all the variations of the experiment and the fork info (SimionFileData.saveExperimentBatchFile())
    - gets the list of available remote machines (herd agents)
    - creates the MonitorWindowViewModel
    - calls MonitorWindowViewModel.runExperiments(), which creates the ExperimentQueueMonitorViewModel object and calls runExperimentsAsync() from a new task (a different thread from the one updating the UI).

So far, the experiments to be run are passed to ExperimentQueueMonitorViewModel via its constructor, but this prevents this class to receive the fork info. The class knows what experimental units -simion.exp files- to run, but cannot tell what value they took for each fork, which we need to display the monitoring data related to forks instead of the experiment's name (which is rather meaningless).
So instead of this, forks and experiments should be read directly from the batch file instead of passed as an argument, so that experiments are related to forks. The format of the batch file can be found here:
https://github.com/borjafdezgauna/RLSimion/wiki/File-types#experiment-batch-simionbatch

**Comment by borjafdezgauna** [comment]
To read the batch file, you should use Data.SimionFileData.loadExperimentBatch(). This method takes a delegate function as parameter that is executed for each of the nodes. An example can be found in ReportsWindowViewModel.loadExperimentBatch()

**Comment by alegd** [comment]
The thing is I already achieved to show fork values in each experiment in queue. What I've done is to pass the fork values along with the name, prerequisites list, etc. when experiment is created and then get those forks values from MonitoredExperimentViewModel the same way we do with experiment's names for instance. But thinking this through your idea for this solution may be way more elegant. I'll see what I can do :)

**Comment by borjafdezgauna** [comment]
ahhh... now I get how you managed to show fork values without reading the batch file! :)
yes, if you don't mind, I'd rather have the batch file read again instead of passing the arguments. This might be handy if we want to reproduce an experiment without having to load it in Badger first. Not sure we will do it but might make testing easier...might

**Comment by alegd** [comment]
Ok. No problem, I'll do that. 

By the way, I haven't yet dig deep into that piece of code, so I was wondering if it would be possible to reuse those classes use in the delegate functions that are passed as parameters to SimionFileData.loadExperimentBatch() in ReportsWindowViewModel, I'm refereing to LoggedExperimentViewModel or LoggedForkViewModel to mention some.

**Comment by borjafdezgauna** [comment]
Yes, I think you can reuse them... they are very simple classes with references to children, so you can add whatever functionality to want to them.
