### ISSUE TITLE
Badger.ExperimentMonitor: organize experiments by forks

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#97]
As in the ReportViewer, experiments should be organized using fork names and values instead, to better understand what's happening: which values are working and which are not.

**Comment by alegd** [comment]
With this you mean somenthing like this?

![example](https://cloud.githubusercontent.com/assets/5748446/24839806/5092b230-1d2f-11e7-8c9c-fa9e899a8f21.jpg)

**Comment by borjafdezgauna** [comment]
That's not what I had in mind, but yep... that works too :) more than fine!

2017-04-09 20:21 GMT+02:00 José Alejandro Guerra Denis <
notifications@github.com>:

**Comment by alegd** [comment]
Well... Can you tell me what do you have in mind?

**Comment by borjafdezgauna** [comment]
Nah, nah, it's ok!

2017-04-10 20:40 GMT+02:00 José Alejandro Guerra Denis <
notifications@github.com>:
