### ISSUE TITLE
Badger.ReportViewer: display stats in a hierarchical structure

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#99]
If possible, group forks and values. For example, if we have two forks in an experiment named "test": alpha {0.1,0.2,0.3} and scale {1,1.5,1.8}, then the results should be grouped similar to this:

> 
>      experiment           alpha          scale      stats
>                                            1         ...
>                             0.1            1.5       ...
>                                            1.8       ...
>                                            1          ...
>        test                 0.2            1.5       ...
>                                            1.8       ...
>                                            1          ...
>                             0.3            1.5       ...
>                                            1.8       ...
>

**Comment by ladm2110** [comment]
Do all groupIds have the same structure? (alpha=value,scale=otherValue)
Is it possible for an experiment to have more than two forks?

**Comment by borjafdezgauna** [comment]
Yes, experiments can have any number of forks (even none) and they may be nested one inside another. You can open an experiment from /experiments/examples, right-click on some parameters, fork them and launch the experiment to see the result and the batch file (Badger will ask you where you want it saved).

**Comment by ladm2110** [comment]
Now that we are displaying all episodes stats, it seems impossible to show all group statistics at the same time...

**Comment by borjafdezgauna** [comment]
Not sure I understand what you mean by "all episodes stats"... could you please attach a screen capture?

**Comment by ladm2110** [comment]
![screen](https://user-images.githubusercontent.com/17488596/27264592-fe50fb32-544f-11e7-9bf5-45f062d5b7f9.png)

**Comment by borjafdezgauna** [comment]
Ok, I think there has been some missunderstanding here... #100 isn't about showing all the evaluation episodes of the experiment, but all the episodes of the evaluation being shown. Normally, only the last evaluation (this is selected when creating the report)
That is, if we use two episodes in each evaluation, we want to show the results of the last evaluation's two episodes, not the stats of all the evaluations during the experiment.

**Comment by borjafdezgauna** [comment]
I think it works reasonably well as it is, without a hierchachical organization of the forks, which is by no means trivial
